
DELETE FROM CC_EVENT_BY_CARD_BY_MINUTE;

DELETE FROM CC_EVENT_HOPPING_WINDOW;

DELETE FROM CC_EVENT_SLIDING_WINDOW;

DELETE FROM CC_EVENT_TUMBLING_WINDOW;

DELETE FROM CC_EVENT_ARBITRARY_TUMBLING_WINDOW;

DELETE FROM CC_EVENT_SESSION_WINDOW;

DELETE FROM CC_EVENT_LAST_20;

DELETE FROM cc_event_arbitrary_tumbling_window;
